# Generated by Django 3.1.6 on 2021-03-22 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homebook', '0004_remove_book_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cart', '0004_auto_20210322_0244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='c_book',
        ),
        migrations.RemoveField(
            model_name='cartproduct',
            name='c_cart',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='book_in_cart', to='homebook.book', verbose_name='Книга в корзине'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='cart.cart', verbose_name='Корзина'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Покупатель'),
        ),
    ]
