# Generated by Django 3.1.6 on 2021-03-21 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0004_auto_20210322_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=40, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=22, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Адрес')),
                ('purchase_type', models.CharField(blank=True, max_length=80, null=True)),
                ('comment', models.TextField(blank=True, max_length=255, null=True, verbose_name='Комментарий')),
                ('created_date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Дата изменения')),
                ('cart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart', verbose_name='Корзина')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_orders', to='accounts.customer', verbose_name='Пользоапте')),
            ],
        ),
    ]
