# Generated by Django 3.1.6 on 2021-03-20 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordbook', '0001_initial'),
        ('homebook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название книги')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Фото обложки')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Цена (BYN)')),
                ('year', models.SmallIntegerField(blank=True, null=True, verbose_name='Год издания')),
                ('pages', models.SmallIntegerField(blank=True, null=True, verbose_name='Страницы')),
                ('cover', models.CharField(blank=True, max_length=20, null=True, verbose_name='Переплет')),
                ('forma', models.CharField(blank=True, max_length=20, null=True, verbose_name='Формат')),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, verbose_name='ISBN')),
                ('weight', models.SmallIntegerField(blank=True, null=True, verbose_name='Вес (гр)')),
                ('age_stat', models.SmallIntegerField(blank=True, null=True, verbose_name='Возрастные ограничения')),
                ('total', models.SmallIntegerField(blank=True, null=True, verbose_name='Книг в наличии')),
                ('active', models.BooleanField(default=True, verbose_name='Доступен Да/Нет')),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Рейтинг')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки')),
                ('authors', models.ManyToManyField(blank=True, to='wordbook.Authors', verbose_name='Авторы книги')),
                ('genres', models.ManyToManyField(blank=True, to='wordbook.Genres', verbose_name='Жанры')),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wordbook.publishers')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='wordbook.series', verbose_name='Серия')),
            ],
        ),
        migrations.DeleteModel(
            name='BookCard',
        ),
    ]
